
trigger:
- main

pool:
  vmImage: windows-latest
  
steps: 
   
- script: |
           echo $(LT_USERNAME)
           echo $(LT_ACCESS_KEY)
           curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
           
           hyperexecute.exe -u $(LT_USERNAME) -k $(LT_ACCESS_KEY) -i yaml/win/.hyperexecute_autosplits.yaml --verbose
