
trigger:
- main

pool:
  vmImage: windows-latest
variables:
- name: LT_USERNAME
  value: $LT_USERNAME
- name:  LT_ACCESS_KEY
  value: $LT_ACCESS_KEY
steps: 

- script: |
           curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe
           
           hyperexecute.exe -u $LT_USERNAME -k $LT_ACCESS_KEY -i yaml/win/.hyperexecute_autosplits.yaml --verbose
