name: Hyperexecute-Playwright
on:
  workflow_dispatch:
    inputs:
      lt_username:
        description: 'LT Username'
        required: true
      lt_accesskey:
        description: 'LT Access Key'
        required: true

jobs:
  Hyperexecute-Playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
          ./hyperexecute --user ${{ github.event.inputs.lt_username }} --key ${{ github.event.inputs.lt_accesskey }} --download-artifacts --config yaml/win/.hyperexecute_autosplits.yaml
          echo "Test completion"
